source_type: LC8_30_1
output_type: LC8_30_1_tiled

description: Landsat-8 16 days in year (Identity cube)

location: '/data/ingested/'
file_path_template: 'LC8_30_1_tiled_ingested/LC8_30_1_tiled_ingested_{tile_index[0]}_{tile_index[1]}_{start_time}.nc'

global_attributes:
    title: Landsat-8 16 days in year - Tiled Identity Cube
    summary: Landsat-8 cube
    source: Landsat-8 version 1
    institution: INPE
    instrument: OLI
    cdm_data_type: Grid
    keywords: REFLECTANCE,LC8,EARTH SCIENCE
    platform: LC81
    processing_level: L2
    product_version: 'v001'
    product_suite: INPE LC8
    project: BDC
    naming_authority: bdc.inpe

storage:
    driver: NetCDF CF

    crs: +proj=aea +lat_0=-12 +lon_0=-54 +lat_1=-2 +lat_2=-22 +x_0=5000000 +y_0=10000000 +ellps=GRS80 +units=m +no_defs
    tile_size:
            x: 100000.0
            y: 100000.0
    resolution:
            x: 30
            y: -30
    chunking:
        x: 256
        y: 256
        time: 1
    dimension_order: ['time', 'y', 'x']

measurements:
    - name: band1
      dtype: int16
      nodata: -9999
      resampling_method: nearest
      src_varname: 'band1'
      zlib: True

    - name:
      dtype: int16
      nodata: -9999
      resampling_method: nearest
      src_varname: 'band2'
      zlib: True
      attrs:
        alias: "blue"

    - name: band3
      dtype: int16
      nodata: -9999
      resampling_method: nearest
      src_varname: 'band3'
      zlib: True
      attrs:
        alias: "green"

    - name: band4
      dtype: int16
      nodata: -9999
      resampling_method: nearest
      src_varname: 'band4'
      zlib: True
      attrs:
        alias: "red"

    - name: band5
      dtype: int16
      nodata: -9999
      resampling_method: nearest
      src_varname: 'band4'
      zlib: True

    - name: band6
      dtype: int16
      nodata: -9999
      resampling_method: nearest
      src_varname: 'band6'
      zlib: True

    - name: band7
      dtype: int16
      nodata: -9999
      resampling_method: nearest
      src_varname: 'band7'
      zlib: True
