source_type: S2_10_16D_STK_1
output_type: S2_10_16D_STK_1_ingested

description: Sentinel 2A/2B 16 days in year

location: '/data/ingested/'
file_path_template: 'S2_10_16D_STK_1_ingested/S2_10_16D_STK_1_ingested_{tile_index[0]}_{tile_index[1]}_{start_time}.nc'

global_attributes:
    title: Sentinel-2 (MSI) Cube Stack 16 days (v001) - Tiled
    summary: Sentinel-2 data product
    source: Sentinel-2 Copernicus
    institution: INPE
    instrument: MSI
    cdm_data_type: Grid
    keywords: REFLECTANCE,S2,EARTH SCIENCE
    platform: S2
    processing_level: L2
    product_version: 'v001'
    product_suite: COPERNICUS S2
    project: BDC
    naming_authority: bdc.inpe
    acknowledgment: S2 is provided by the Copernicus

storage:
    driver: NetCDF CF

    crs: +proj=aea +lat_0=-12 +lon_0=-54 +lat_1=-2 +lat_2=-22 +x_0=5000000 +y_0=10000000 +ellps=GRS80 +units=m +no_defs
    tile_size:
            x: 150000.0
            y: 150000.0
    resolution:
            x: 64
            y: -64
    chunking:
        x: 200
        y: 200
        time: 1
    dimension_order: ['time', 'y', 'x']

measurements:
    - name: band11
      dtype: int16
      nodata: -9999
      resampling_method: nearest
      src_varname: 'band11'
      zlib: True
      attrs:
        alias: "swir1"

    - name: band12
      dtype: int16
      nodata: -9999
      resampling_method: nearest
      src_varname: 'band12'
      zlib: True
      attrs:
        alias: "swir2"

    - name: band2
      dtype: int16
      nodata: -9999
      resampling_method: nearest
      src_varname: 'band2'
      zlib: True
      attrs:
        alias: "blue"

    - name: band3
      dtype: int16
      nodata: -9999
      resampling_method: nearest
      src_varname: 'band3'
      zlib: True
      attrs:
        alias: "green"

    - name: band4
      dtype: int16
      nodata: -9999
      resampling_method: nearest
      src_varname: 'band4'
      zlib: True
      attrs:
        alias: "red"

    - name: band5
      dtype: int16
      nodata: -9999
      resampling_method: nearest
      src_varname: 'band5'
      zlib: True
      attrs:
        alias: "redge1"

    - name: band6
      dtype: int16
      nodata: -9999
      resampling_method: nearest
      src_varname: 'band6'
      zlib: True
      attrs:
        alias: "redge2"

    - name: band7
      dtype: int16
      nodata: -9999
      resampling_method: nearest
      src_varname: 'band7'
      zlib: True
      attrs:
        alias: "redge3"

    - name: band8
      dtype: int16
      nodata: -9999
      resampling_method: nearest
      src_varname: 'band8'
      zlib: True
      attrs:
        alias: "bnir"

    - name: band8a
      dtype: int16
      nodata: -9999
      resampling_method: nearest
      src_varname: 'band8a'
      zlib: True
      attrs:
        alias: "nir"

    - name: EVI
      dtype: int16
      nodata: -9999
      resampling_method: nearest
      src_varname: 'EVI'
      zlib: True
      attrs:
        alias: "evi"

    - name: NDVI
      dtype: int16
      nodata: -9999
      resampling_method: nearest
      src_varname: 'NDVI'
      zlib: True
      attrs:
        alias: "ndvi"
