version: "3.2"

services:
  scheduler:
    image: daskdev/dask:2.27.0
    hostname: dask-scheduler
    ports:
      - "8786:8786"
      - "8787:8787"
    command: ["dask-scheduler"]
    networks:
      - bdc-odc-net

  worker:
    build:
      context: ../
      dockerfile: dask-runner/Dockerfile
    hostname: dask-worker
    env_file:
      - .env
    volumes:
      - type: bind
        source: ${DATA_DIR_SOURCE}
        target: ${DATA_DIR_TARGET}
    command: ["dask-worker", "tcp://scheduler:8786"]
    networks:
      - bdc-odc-net

  odc-stats:
    build:
      context: ../
      dockerfile: datacube-stats/Dockerfile
    hostname: bdc-odc-stats
    env_file:
      - .env
    volumes:
      - type: bind
        source: ${DATA_DIR_SOURCE}
        target: ${DATA_DIR_TARGET}
    tty: true
    stdin_open: true
    entrypoint: python3
    networks:
      - bdc-odc-net

networks:
  bdc-odc-net:
    external: true
